### ISSUE TITLE
Network videos - black screen

### ISSUE THREAD

**Issue by Charlsburg** [theothernt/AerialDream#14]
Afternoon,
firstly - thanks for all your hard work here, particularly love the anti-burn in option for added peace of mind!

I've downloaded all the Apple videos in 4k HDR and host them on my NAS (Unraid) with open permissions.
When I add the network details and hit test, it sees all the videos in that share (88 videos found).

When I go to test/start the screensaver however, its a black screen only.  Now I know you've said HDR videos dont play correctly for everyone, however when switching to the streamed option from Apple servers (and selecting HDR only), they play in Dolby vision no probs.  Its just not playing from the network share.

Additionally, when I pop 4k SDR versions in the network folder instead, same issue black screen.
Finally, I grabbed some 1080p HDR and SDR videos and put them in the share - black screen, wont play.

For all these, when you hit the "right" button on the remote it flashes the filename and time before returning to black image.

Im running v0.98.1 release build on an Nvidia Shield Pro, displaying onto a 4k 55" OLED LG GX, running a gigabit ethernet connection (Plays 4k HDR content on a regular basis via Plex).  The network share is SMB open permissions.

**Comment by jaqarll** [comment]
I have literally the same issues as described above with a LG Oled and Chromecast with Google TV. The app also reports that neither 4k nor DV are supposedly supported by the device.

**Comment by Charlsburg** [comment]
I have been able to find a work-around for the Shield - unsure how/if this would work for other devices.

On the shield, you can mount network storage - head to Device Preferences > Storage > Mount Network Storage > Add your SMB drive here.  I created a SMB share with no permissions that the shield can freely access called "Screensavers".

Once this is mounted, it acts as if it was Shield internal storage which means you can use Arial Dreams "Apple TV Videos" mode set to "Location - Local Only".
Disable Local Videos and Network Videos mode.

The app will search the shield, locate your mounted network drive, and play the videos from the network (Works in 4k HDR Dolby Vision).

**Comment by theothernt** [comment]
Thanks for reporting the issue, has it happened with previous versions? @jaqarll @Charlsburg

**Comment by jaqarll** [comment]
Yes, so far I haven't been able to use my smb for the task. Sorry for not reporting it earlier, but so far no smb version of the app was able to play the files. I then just used the online function of the app.

**Comment by theothernt** [comment]
@jaqarll Apologies for the issue, it may just be happening to Shield users (which is odd ?!) as I did get a few crash reports in the last few days.

I will hopefully put out a fix in the next couple of days (0.98.2 probably)

Btw - in Network Videos, did the 'Test connection settings' option work?

**Comment by Charlsburg** [comment]
> @jaqarll Apologies for the issue, it may just be happening to Shield users (which is odd ?!) as I did get a few crash reports in the last few days.
> 
> I will hopefully put out a fix in the next couple of days (0.98.2 probably)
> 
> Btw - in Network Videos, did the 'Test connection settings' option work?

Only just started using this sorry so can't comment on previous versions.
User jaqarll isn't on the Shield he has a Google TV so not just isolated to Shield apparently.

Yes the network test works perfect, showed the video count in folder without fail.

**Comment by jaqarll** [comment]
Yes, am on Chromecast and the test connection correctly reports the correct number of files.

**Comment by theothernt** [comment]
Thanks to you both for that info, I think have I have a good idea what the issue is. I'll have a new build tomorrow which hopefully fixes the issue.

**Comment by theothernt** [comment]
@Charlsburg @jaqarll Just one more quick question...

Can you check in Settings > Network Videos > Share Name - does the share name start with a forward slash and NOT end with a forward slash?

eg. /share/videos - not share/videos or /share/videos/ etc

(I'm trying to rule out a more obvious issue)

**Comment by jaqarll** [comment]
It starts with a / and ends without. Adding / at the end seems to fix it a little bit, as I'm now able to see videos when testing the setting. However, it takes a lot of time for them to load then and they only play for about a second and then stop.

**Comment by Charlsburg** [comment]
> @Charlsburg @jaqarll Just one more quick question...
> 
> Can you check in Settings > Network Videos > Share Name - does the share name start with a forward slash and NOT end with a forward slash?
> 
> eg. /share/videos - not share/videos or /share/videos/ etc
> 
> (I'm trying to rule out a more obvious issue)

Interesting find: I always close my file paths so went back into the Share Name and it showed as "/Screensavers".
I changed it back to "/Screensavers/" - Hit okay.  Opened Share Name up again, confirmed it to be "/Screensavers/"
Hit test - Black screen.
Went back to Share Name and it had reverted to "/Screensavers"

**Comment by jaqarll** [comment]
> > @Charlsburg @jaqarll Just one more quick question...
> > Can you check in Settings > Network Videos > Share Name - does the share name start with a forward slash and NOT end with a forward slash?
> > eg. /share/videos - not share/videos or /share/videos/ etc
> > (I'm trying to rule out a more obvious issue)
> 
> Interesting find: I always close my file paths so went back into the Share Name and it showed as "/Screensavers".
> I changed it back to "/Screensavers/" - Hit okay. Opened Share Name up again, confirmed it to be "/Screensavers/"
> Hit test - Black screen.
> Went back to Share Name and it had reverted to "/Screensavers"

Have you tried waiting for a few seconds? After including / the videos loaded after 10-20 sec.

**Comment by Charlsburg** [comment]
> > > @Charlsburg @jaqarll Just one more quick question...
> > > Can you check in Settings > Network Videos > Share Name - does the share name start with a forward slash and NOT end with a forward slash?
> > > eg. /share/videos - not share/videos or /share/videos/ etc
> > > (I'm trying to rule out a more obvious issue)
> > 
> > 
> > Interesting find: I always close my file paths so went back into the Share Name and it showed as "/Screensavers".
> > I changed it back to "/Screensavers/" - Hit okay. Opened Share Name up again, confirmed it to be "/Screensavers/"
> > Hit test - Black screen.
> > Went back to Share Name and it had reverted to "/Screensavers"
> 
> Have you tried waiting for a few seconds? After including / the videos loaded after 10-20 sec.

Just tested now, after 60 secs nothing.

**Comment by theothernt** [comment]
So just to explain what's going on here...

The SMB/Network stuff is very particular when it comes to paths. One extra slash and nothing works - more so with the video player than the network connection itself.

On the Network Videos screen, when you enter a 'share name' it actually checks + fixes the entry. But due to a quirk, the text box that pops up won't show the 'corrected' entry until you go back to the main Settings screen, then into Network Video screen and check again.

**Comment by theothernt** [comment]
Another question for @Charlsburg and @jaqarll 

Regarding the 'Share Name' you use, is it just 1 folder level and not multiple eg. /videos vs /videos/aerial/apple

**Comment by jaqarll** [comment]
Multiple folders on my end.

**Comment by Charlsburg** [comment]
> Another question for @Charlsburg and @jaqarll
> 
> Regarding the 'Share Name' you use, is it just 1 folder level and not multiple eg. /videos vs /videos/aerial/apple
> 
> Also, do you use a username + password for that SMB share?

Single folder for me - using the most direct path possible (Literally 192.168.1.10/Screensavers/)

**Comment by nirajsanghvi** [comment]
> It starts with a / and ends without. Adding / at the end seems to fix it a little bit, as I'm now able to see videos when testing the setting. However, it takes a lot of time for them to load then and they only play for about a second and then stop.

Wow, this tip about adding the slash to the end fixed a couple of my videos that were only showing a black screen so thanks @jaqarll! Out of 20 videos I have in my folder, probably about 3 (always the same 3) consistently showed a black screen, and one was doing some odd stretching even though it had the same aspect ratio as the rest (that stretched one was a new video so this may have just been some weird one-time issue, I didn't get to try to reproduce it, but adding the slash seems to have fixed its playback too). I have multiple subfolders and username/password as well.

**Comment by theothernt** [comment]
> Wow, this tip about adding the slash to the end fixed a couple of my network videos that were only showing a black screen so thanks @jaqarll! Out of 20 videos I have in my folder, probably about 3 (always the same 3) consistently showed a black screen, and one was doing some odd stretching even though it had the same aspect ratio as the rest (that stretched one was a new video so this may have just been some weird one-time issue, I didn't get to try to reproduce it, but adding the slash seems to have fixed its playback too). I have multiple subfolders and username/password as well.

That is odd! typically, the URL to the video is either valid or invalid - meaning it'll play or you'll get a black screen. Seeing a different aspect ratio is... strange ?!

But from the feedback so far, it does seem like there's a bug (or two) in my URL parsing code so I'm currently rewriting some of it.

**Comment by theothernt** [comment]
Ok, I've just released 0.98.2... https://github.com/theothernt/AerialDream/releases/tag/0.98.2-preview

Give it a try when you have time and let me know if it fixes anything, or not!

**Comment by jaqarll** [comment]
Issues persist, videos take about 25sec to load, play for a second and then stop.

**Comment by theothernt** [comment]
> Issues persist, videos take about 25sec to load, play for a second and then stop.

Have you tried copying one of those videos to local storage and seeing if it plays ok?

**Comment by jaqarll** [comment]
I don't have a USB hub I could try this with. All videos however are all the official apple videos.

**Comment by theothernt** [comment]
> I don't have a USB hub I could try this with. All videos however are all the official apple videos.

Would you mind trying the following file, it's only 30MB + H.264 so it should play well on anything... 

https://github.com/glouel/AerialCommunity/releases/download/mw2-1080p-h264/video_inspire_florida_miami_brickell_sunset_00036.1080-h264.mov

(taken from: https://github.com/glouel/AerialCommunity/releases/tag/mw2-4k-sdr)

**Comment by Charlsburg** [comment]
Latest update fixed the issue my end, finds all files within network share and plays them instantly at full quality. 
The only difference I've noticed now is that it displays the file name, whereas when using the "Apple TV Videos" mode this must use a pre-defined list that shows video location/name.  I'm assuming I should just rename all my videos?

**Comment by Charlsburg** [comment]
> Latest update fixed the issue my end, finds all files within network share and plays them instantly - however I am noticing reduced FPS which makes busy videos (like the fish ones) look quite bad, trippy even!.
> 
> The only other difference I've noticed now is that it displays the file name, whereas when using the "Apple TV Videos" mode this must use a pre-defined list that shows video location/name. I'm assuming I should just rename all my videos?

Actually further to this, during app-test the FPS looks the same between network and local file share, it looks to be an issue only when a video is paused in the background.

Just tested using local file share, and a video on pause, waited 5mins and the FPS drops dramatically- so its nothing to do with this issue, assuming it's memory related.

**Comment by jaqarll** [comment]
> > I don't have a USB hub I could try this with. All videos however are all the official apple videos.
> 
> Would you mind trying the following file, it's only 30MB + H.264 so it should play well on anything...
> 
> https://github.com/glouel/AerialCommunity/releases/download/mw2-1080p-h264/video_inspire_florida_miami_brickell_sunset_00036.1080-h264.mov
> 
> (taken from: https://github.com/glouel/AerialCommunity/releases/tag/mw2-4k-sdr)

On the newest version: this video doesn't play at all for me. For the record the app shows that the render capabilities are supposedly only HD while the Chromecast as well as my LG Oled support 4k and DV.

**Comment by theothernt** [comment]
> > Latest update fixed the issue my end, finds all files within network share and plays them instantly - however I am noticing reduced FPS which makes busy videos (like the fish ones) look quite bad, trippy even!.
> > The only other difference I've noticed now is that it displays the file name, whereas when using the "Apple TV Videos" mode this must use a pre-defined list that shows video location/name. I'm assuming I should just rename all my videos?
> 
> Actually further to this, during app-test the FPS looks the same between network and local file share, it looks to be an issue only when a video is paused in the background.
> 
> Just tested using local file share, and a video on pause, waited 5mins and the FPS drops dramatically- so its nothing to do with this issue, assuming it's memory related.

About the location support, it's not there for Network Videos but it will be in the next build. I'll be changing the menu options to make it a little simpler too.

As for the frame rate issue you're seeing, the only thing I can suggest trying (and it's just a guess really!) is turning off Enable Tunneling in Performance & Debug options

**Comment by theothernt** [comment]
> > > I don't have a USB hub I could try this with. All videos however are all the official apple videos.
> > 
> > 
> > Would you mind trying the following file, it's only 30MB + H.264 so it should play well on anything...
> > https://github.com/glouel/AerialCommunity/releases/download/mw2-1080p-h264/video_inspire_florida_miami_brickell_sunset_00036.1080-h264.mov
> > (taken from: https://github.com/glouel/AerialCommunity/releases/tag/mw2-4k-sdr)
> 
> On the newest version: this video doesn't play at all for me. For the record the app shows that the render capabilities are supposedly only HD while the Chromecast as well as my LG Oled support 4k and DV.

For the moment, you can ignore the Capabilities screen. I added it hoping it would give useful info but it doesn't appear to be accurate. My old 2015 TV reports 'Yes' to HDR which is impossible!

That aside, there some other playback issues so we should focus on that. If you can move your Apple videos (I assume they're 4K HDR) to another folder, then try videos from...https://aerial-videos.netlify.app/

What I'd suggest is downloading is one of the lowest quality (1080p SDR) videos, then trying that. If that works, try 1080p HDR, then 4K SDR and so on.

(Also, I have a Google TV too so I know it can play 4K HDR videos even on a non-HDR TV, it tone-maps it down to SDR for me so the videos don't look green like if play them with VLC on Mac or PC)

**Comment by jaqarll** [comment]
Tested all three kinds of videos and none of them work. I just get a black screen with all of them. I can play them all fine with a MX ayer for example.

**Comment by theothernt** [comment]
> Tested all three kinds of videos and none of them work. I just get a black screen with all of them. I can play them all fine with a MX ayer for example.
> 
> Edit: I get the feeling this might be some router specific issues maybe? I'm using the smb share of my avm fritz box router and encountered similar issues with the nova video app. Maybe there are similarities? Link for reference: [nova-video-player/aos-AVP#413](https://github.com/nova-video-player/aos-AVP/issues/413)

From your earlier reports (delays before seeing anything, etc) it did sound network related. Have you tried both IP and hostname? (hostnames don't work for me, for example)

**Comment by jaqarll** [comment]
Changes from ip to hostname, but that changed nothing.

**Comment by theothernt** [comment]
@jaqarll would you mind opening a new issue, maybe something about slow network playback and we can continue to troubleshoot there?

@Charlsburg as the original issue is fixed I may close this soon but I can look into the jerky video playback under a new issue if you like?

**Comment by Charlsburg** [comment]
> @jaqarll would you mind opening a new issue, maybe something about slow network playback and we can continue to troubleshoot there?
> 
> @Charlsburg as the original issue is fixed I may close this soon but I can look into the jerky video playback under a new issue if you like?

I dont even think its something you'll be able to improve as its likely a memory issue with the shield and running two UHD videos at once (even though on is paused, its still in memory presumably)
Otherwise as far as the network issue goes, its working well, I havent switched back over to it yet as Ill need to change all my file names - Thank you for your hard work here!
